export interface LocationItem {
  id: string;
  name: string;
  type: "city" | "airport" | "station" | "landmark";
  city: string;
  state: string;
  lat: number;
  lng: number;
  code?: string;
}

export const LOCATIONS_DATABASE: LocationItem[] = [
  // CITIES
  {
    id: "loc-nashik",
    name: "Nashik, Maharashtra",
    type: "city",
    city: "Nashik",
    state: "Maharashtra",
    lat: 20.0059,
    lng: 73.7898,
  },
  {
    id: "loc-mumbai",
    name: "Mumbai, Maharashtra",
    type: "city",
    city: "Mumbai",
    state: "Maharashtra",
    lat: 19.076,
    lng: 72.8777,
  },
  {
    id: "loc-pune",
    name: "Pune, Maharashtra",
    type: "city",
    city: "Pune",
    state: "Maharashtra",
    lat: 18.5204,
    lng: 73.8567,
  },
  {
    id: "loc-shirdi",
    name: "Shirdi, Maharashtra",
    type: "city",
    city: "Shirdi",
    state: "Maharashtra",
    lat: 19.7645,
    lng: 74.4762,
  },
  {
    id: "loc-surat",
    name: "Surat, Gujarat",
    type: "city",
    city: "Surat",
    state: "Gujarat",
    lat: 21.1702,
    lng: 72.8311,
  },
  {
    id: "loc-thane",
    name: "Thane, Maharashtra",
    type: "city",
    city: "Thane",
    state: "Maharashtra",
    lat: 19.2183,
    lng: 72.9781,
  },
  {
    id: "loc-navi-mumbai",
    name: "Navi Mumbai, Maharashtra",
    type: "city",
    city: "Navi Mumbai",
    state: "Maharashtra",
    lat: 19.033,
    lng: 73.0297,
  },
  {
    id: "loc-lonavala",
    name: "Lonavala, Maharashtra",
    type: "city",
    city: "Lonavala",
    state: "Maharashtra",
    lat: 18.7557,
    lng: 73.4091,
  },
  {
    id: "loc-mahabaleshwar",
    name: "Mahabaleshwar, Maharashtra",
    type: "city",
    city: "Mahabaleshwar",
    state: "Maharashtra",
    lat: 17.9237,
    lng: 73.6586,
  },
  {
    id: "loc-sambhajinagar",
    name: "Chhatrapati Sambhajinagar (Aurangabad)",
    type: "city",
    city: "Chhatrapati Sambhajinagar",
    state: "Maharashtra",
    lat: 19.8762,
    lng: 75.3433,
  },
  {
    id: "loc-goa",
    name: "Goa (North / South)",
    type: "city",
    city: "Goa",
    state: "Goa",
    lat: 15.2993,
    lng: 74.124,
  },
  {
    id: "loc-ahmedabad",
    name: "Ahmedabad, Gujarat",
    type: "city",
    city: "Ahmedabad",
    state: "Gujarat",
    lat: 23.0225,
    lng: 72.5714,
  },
  {
    id: "loc-trimbakeshwar",
    name: "Trimbakeshwar, Nashik",
    type: "city",
    city: "Trimbakeshwar",
    state: "Maharashtra",
    lat: 19.9324,
    lng: 73.5303,
  },

  // AIRPORTS
  {
    id: "loc-bom-airport",
    name: "Chhatrapati Shivaji Maharaj International Airport (BOM), Mumbai",
    type: "airport",
    city: "Mumbai",
    state: "Maharashtra",
    code: "BOM",
    lat: 19.0896,
    lng: 72.8656,
  },
  {
    id: "loc-pnq-airport",
    name: "Pune International Airport (PNQ), Lohegaon Pune",
    type: "airport",
    city: "Pune",
    state: "Maharashtra",
    code: "PNQ",
    lat: 18.5822,
    lng: 73.9197,
  },
  {
    id: "loc-ozar-airport",
    name: "Nashik Airport (ISK/Ozar), Nashik",
    type: "airport",
    city: "Nashik",
    state: "Maharashtra",
    code: "ISK",
    lat: 20.1163,
    lng: 73.9142,
  },
  {
    id: "loc-stv-airport",
    name: "Surat International Airport (STV), Surat",
    type: "airport",
    city: "Surat",
    state: "Gujarat",
    code: "STV",
    lat: 21.1141,
    lng: 72.7418,
  },
  {
    id: "loc-sag-airport",
    name: "Shirdi International Airport (SAG), Kakadi Shirdi",
    type: "airport",
    city: "Shirdi",
    state: "Maharashtra",
    code: "SAG",
    lat: 19.6896,
    lng: 74.3789,
  },
  {
    id: "loc-gox-airport",
    name: "Manohar International Airport (Mopa GOX), Goa",
    type: "airport",
    city: "Goa",
    state: "Goa",
    code: "GOX",
    lat: 15.7381,
    lng: 73.8658,
  },

  // RAILWAY STATIONS
  {
    id: "loc-nashik-station",
    name: "Nashik Road Railway Station (NK), Nashik",
    type: "station",
    city: "Nashik",
    state: "Maharashtra",
    code: "NK",
    lat: 19.9482,
    lng: 73.8344,
  },
  {
    id: "loc-cst-station",
    name: "Chhatrapati Shivaji Maharaj Terminus (CSMT), Mumbai",
    type: "station",
    city: "Mumbai",
    state: "Maharashtra",
    code: "CSMT",
    lat: 18.9402,
    lng: 72.835,
  },
  {
    id: "loc-pune-station",
    name: "Pune Junction Railway Station (PUNE), Pune",
    type: "station",
    city: "Pune",
    state: "Maharashtra",
    code: "PUNE",
    lat: 18.5284,
    lng: 73.8744,
  },
  {
    id: "loc-surat-station",
    name: "Surat Junction Railway Station (ST), Surat",
    type: "station",
    city: "Surat",
    state: "Gujarat",
    code: "ST",
    lat: 21.2048,
    lng: 72.8406,
  },

  // LANDMARKS
  {
    id: "loc-bkc-mumbai",
    name: "Bandra Kurla Complex (BKC), Mumbai",
    type: "landmark",
    city: "Mumbai",
    state: "Maharashtra",
    lat: 19.0657,
    lng: 72.8687,
  },
  {
    id: "loc-hinjewadi",
    name: "Hinjewadi IT Park, Pune",
    type: "landmark",
    city: "Pune",
    state: "Maharashtra",
    lat: 18.5912,
    lng: 73.7389,
  },
];
