import { FleetVehicle, ServiceItem, FaqItem, Testimonial } from "@/types";

export const MOCK_FLEET: FleetVehicle[] = [
  {
    id: "dzire",
    name: "Maruti Dzire / Etios",
    category: "Economy",
    capacity: "4 Seats",
    seats: "4 Seats",
    transmission: "Manual",
    luggage: "2 Bags",
    ac: true,
    ratePerKm: "₹11/km",
    startingPrice: "₹1,499",
    pricePerDay: "₹1,499 /day",
    image: "/images/listing/listing-2-1.jpg",
    popular: true,
  },
  {
    id: "honda-city",
    name: "Honda City / Verna",
    category: "Sedan",
    capacity: "4 Seats",
    seats: "4 Seats",
    transmission: "Auto",
    luggage: "2 Bags",
    ac: true,
    ratePerKm: "₹13/km",
    startingPrice: "₹1,800",
    pricePerDay: "₹1,800 /day",
    image: "/images/listing/listing-2-2.jpg",
    popular: true,
  },
  {
    id: "ertiga",
    name: "Ertiga / Triber",
    category: "Family MPV",
    capacity: "6 Seats",
    seats: "6 Seats",
    transmission: "Manual",
    luggage: "3 Bags",
    ac: true,
    ratePerKm: "₹15/km",
    startingPrice: "₹2,199",
    pricePerDay: "₹2,199 /day",
    image: "/images/listing/listing-2-3.jpg",
    popular: true,
  },
  {
    id: "innova-crysta",
    name: "Toyota Innova Crysta",
    category: "Luxury SUV",
    capacity: "7 Seats",
    seats: "7 Seats",
    transmission: "Auto",
    luggage: "4 Bags",
    ac: true,
    ratePerKm: "₹18/km",
    startingPrice: "₹2,999",
    pricePerDay: "₹2,999 /day",
    image: "/images/listing/listing-2-4.jpg",
    popular: true,
  },
  {
    id: "tempo",
    name: "Tempo Traveller",
    category: "Group Travel",
    capacity: "12-16 Seats",
    seats: "16 Seats",
    transmission: "Manual",
    luggage: "8 Bags",
    ac: true,
    ratePerKm: "₹24/km",
    startingPrice: "₹4,500",
    pricePerDay: "₹4,500 /day",
    image: "/images/listing/listing-2-5.jpg",
  },
  {
    id: "audi-a6",
    name: "Audi A6 Luxury",
    category: "Premium Luxury",
    capacity: "4 Seats",
    seats: "4 Seats",
    transmission: "Auto",
    luggage: "3 Bags",
    ac: true,
    ratePerKm: "₹35/km",
    startingPrice: "₹6,500",
    pricePerDay: "₹6,500 /day",
    image: "/images/listing/listing-2-6.jpg",
  },
  {
    id: "bmw-5",
    name: "BMW 5 Series",
    category: "Sports Luxury",
    capacity: "4 Seats",
    seats: "4 Seats",
    transmission: "Auto",
    luggage: "3 Bags",
    ac: true,
    ratePerKm: "₹38/km",
    startingPrice: "₹7,200",
    pricePerDay: "₹7,200 /day",
    image: "/images/listing/listing-2-7.jpg",
    popular: true,
  },
  {
    id: "fortuner",
    name: "Toyota Fortuner 4x4",
    category: "Premium 4x4",
    capacity: "7 Seats",
    seats: "7 Seats",
    transmission: "Auto",
    luggage: "4 Bags",
    ac: true,
    ratePerKm: "₹26/km",
    startingPrice: "₹4,800",
    pricePerDay: "₹4,800 /day",
    image: "/images/listing/listing-2-8.jpg",
  },
];

export const MOCK_SERVICES: ServiceItem[] = [
  {
    id: "outstation",
    title: "Outstation One-Way & Round Trip",
    description: "Comfortable inter-city travel with verified drivers and zero hidden tolls.",
    icon: "Car",
    badge: "Popular",
  },
  {
    id: "airport",
    title: "Airport Pick & Drop",
    description: "On-time airport transfers with flight tracking and free waiting time.",
    icon: "Plane",
  },
  {
    id: "local",
    title: "Hourly Local Rentals",
    description: "Flexible packages (8hrs/80km, 12hrs/120km) for local city errands and meetings.",
    icon: "Clock",
  },
];

export const MOCK_FAQS: FaqItem[] = [
  {
    id: "faq-1",
    question: "Are toll taxes and state driver charges included in the fare?",
    answer: "Yes, our quotes clearly outline base fare, estimated toll charges, and driver allowance so there are no surprises.",
  },
  {
    id: "faq-2",
    question: "Can I cancel my ride booking anytime?",
    answer: "Free cancellation is available up to 4 hours before the scheduled pick-up time.",
  },
  {
    id: "faq-3",
    question: "Are your vehicles sanitized and air-conditioned?",
    answer: "All vehicles undergo regular maintenance and deep cleaning before every journey.",
  },
];

export const MOCK_TESTIMONIALS: Testimonial[] = [
  {
    id: "test-1",
    name: "Rajesh Sharma",
    role: "Business Traveler",
    rating: 5,
    comment: "Punctual driver, clean Innova Crysta, and transparent billing. Highly recommended for airport transfers!",
    location: "Delhi to Jaipur",
  },
  {
    id: "test-2",
    name: "Priya Patel",
    role: "Family Vacation",
    rating: 5,
    comment: "Booked Ertiga for outstation trip. Smooth ride and very courteous driver.",
    location: "Mumbai to Pune",
  },
  {
    id: "test-3",
    name: "Amit Kumar",
    role: "Regular Commuter",
    rating: 5,
    comment: "Best cab service I have ever used. The cars are always well-maintained and the drivers are very professional.",
    location: "Delhi NCR",
  },
  {
    id: "test-4",
    name: "Sneha Reddy",
    role: "Solo Traveler",
    rating: 5,
    comment: "Felt very safe during my late-night airport drop. The driver was polite and reached on time.",
    location: "Hyderabad",
  },
  {
    id: "test-5",
    name: "Vikram Singh",
    role: "Corporate Client",
    rating: 4,
    comment: "We use their services for all our corporate travels. Reliable, easy billing, and great fleet options.",
    location: "Bangalore",
  }
];
